const {app}=require("electron");
const fs=require("fs");
const leituraFs=process.versions.electron?require("original-fs"):fs;
const path=require("path");
const os=require("os");
const sqlite3=require("sqlite3").verbose();
const db=require("../database");

const crcTabela=(()=>{const tabela=[];for(let n=0;n<256;n++){let c=n;for(let k=0;k<8;k++)c=(c&1)?0xedb88320^(c>>>1):c>>>1;tabela[n]=c>>>0;}return tabela;})();
const crc32=buffer=>{let crc=0xffffffff;for(const byte of buffer)crc=crcTabela[(crc^byte)&0xff]^(crc>>>8);return (crc^0xffffffff)>>>0;};
const dataZip=data=>{const recebida=data instanceof Date&&!Number.isNaN(data.getTime())?data:new Date(),minima=new Date(1980,0,1,0,0,0),maxima=new Date(2107,11,31,23,59,58),d=recebida<minima?minima:recebida>maxima?maxima:recebida,hora=(d.getHours()<<11)|(d.getMinutes()<<5)|(d.getSeconds()>>1),dia=((d.getFullYear()-1980)<<9)|((d.getMonth()+1)<<5)|d.getDate();return {hora,dia};};

class BackupService{
    constructor(){this.timerBackupDiario=null;}
    data(){const d=new Date();return `${d.getFullYear()}-${String(d.getMonth()+1).padStart(2,"0")}-${String(d.getDate()).padStart(2,"0")}`;}
    pastaBase(){return path.join(__dirname,"..",".demo-data","backups");}
    arquivoPreferencias(){return path.join(app.getPath("userData"),"backup-preferencias.json");}
    preferencias(){try{return {backupDiarioAtivo:false,horaBackup:"23:55",pastaBackupDiario:"",googleDriveAtivo:false,pastaGoogleDrive:"",...JSON.parse(fs.readFileSync(this.arquivoPreferencias(),"utf8"))};}catch{return {backupDiarioAtivo:false,horaBackup:"23:55",pastaBackupDiario:"",googleDriveAtivo:false,pastaGoogleDrive:""};}}
    salvarPreferencias(dados){const atuais=this.preferencias(),novas={...atuais,...dados};fs.mkdirSync(path.dirname(this.arquivoPreferencias()),{recursive:true});fs.writeFileSync(this.arquivoPreferencias(),JSON.stringify(novas,null,2));return novas;}
    caminhoBanco(){return db.filename;}
    pastaPadraoBackupDiario(){return path.join(this.pastaBase(),"Diarios");}
    pastaDisponivel(pasta){try{return Boolean(pasta&&fs.statSync(pasta).isDirectory()&&(fs.accessSync(pasta,fs.constants.W_OK)===undefined));}catch{return false;}}
    validarPastaBackupDiario(pasta){const escolhida=path.resolve(String(pasta||"")),raizSistema=path.resolve(path.join(__dirname,".."));if(!pasta||!this.pastaDisponivel(escolhida))throw new Error("A pasta selecionada não existe ou não permite gravação.");if(escolhida===raizSistema||escolhida.startsWith(`${raizSistema}${path.sep}`))throw new Error("Escolha uma pasta fora da instalação da aplicação e da pasta do banco em uso.");return escolhida;}
    statusDestinoDiario(){const preferencias=this.preferencias(),padrao=this.pastaPadraoBackupDiario(),configurada=String(preferencias.pastaBackupDiario||"").trim(),disponivel=Boolean(configurada&&this.pastaDisponivel(configurada)),efetiva=disponivel?path.resolve(configurada):padrao;return {pastaBackupDiarioConfigurada:configurada,pastaBackupDiarioEfetiva:efetiva,pastaBackupDiarioPadrao:padrao,pastaBackupDiarioDisponivel:configurada?disponivel:true,usandoDestinoPersonalizado:disponivel,usandoDestinoPadrao:!disponivel};}
    configurarPastaBackupDiario(pasta){const escolhida=this.validarPastaBackupDiario(pasta);this.salvarPreferencias({pastaBackupDiario:escolhida});return {...this.preferencias(),...this.statusDestinoDiario()};}
    restaurarPastaBackupDiarioPadrao(){this.salvarPreferencias({pastaBackupDiario:""});return {...this.preferencias(),...this.statusDestinoDiario()};}
    pastasRetencaoDiaria(){const status=this.statusDestinoDiario(),pastas=new Set([path.resolve(status.pastaBackupDiarioPadrao)]);if(status.pastaBackupDiarioConfigurada&&status.pastaBackupDiarioDisponivel)pastas.add(path.resolve(status.pastaBackupDiarioConfigurada));return [...pastas];}
    dataBackupDiario(nome){const resultado=/^backup_(\d{4})-(\d{2})-(\d{2})\.db$/i.exec(nome);if(!resultado)return null;const ano=Number(resultado[1]),mes=Number(resultado[2]),dia=Number(resultado[3]),data=new Date(ano,mes-1,dia);return data.getFullYear()===ano&&data.getMonth()===mes-1&&data.getDate()===dia?data:null;}
    async limparBackupsDiariosAntigos(referencia=new Date()){const limite=new Date(referencia);limite.setHours(0,0,0,0);limite.setDate(limite.getDate()-29);const removidos=[];for(const pasta of this.pastasRetencaoDiaria()){if(!fs.existsSync(pasta))continue;let entradas;try{entradas=await fs.promises.readdir(pasta,{withFileTypes:true});}catch(erro){console.error("Retenção dos backups diários:",erro.message);continue;}for(const entrada of entradas){if(!entrada.isFile())continue;const data=this.dataBackupDiario(entrada.name);if(!data||data>=limite)continue;const arquivo=path.join(pasta,entrada.name);try{await fs.promises.unlink(arquivo);removidos.push(arquivo);}catch(erro){console.error(`Não foi possível remover o backup antigo ${arquivo}:`,erro.message);}}}return {removidos,limite:limite.toISOString()};}
    validarBanco(arquivo,exigirEstrutura=true){return new Promise((resolve,reject)=>{if(!arquivo||!fs.existsSync(arquivo))return reject(new Error("O arquivo de backup não existe."));if(fs.statSync(arquivo).size===0)return reject(new Error("O arquivo de backup está vazio."));const copia=new sqlite3.Database(arquivo,sqlite3.OPEN_READONLY,erro=>{if(erro)return reject(new Error(`Não foi possível abrir o backup: ${erro.message}`));copia.get("PRAGMA integrity_check",[],(erroIntegridade,resultado)=>{if(erroIntegridade||!resultado||resultado.integrity_check!=="ok")return copia.close(()=>reject(new Error(`O backup está corrompido: ${erroIntegridade?.message||resultado?.integrity_check||"falha de integridade"}`)));if(!exigirEstrutura)return copia.close(erroFechar=>erroFechar?reject(erroFechar):resolve({arquivo,tamanho:fs.statSync(arquivo).size}));const obrigatorias=["usuarios","equipamentos","cautelas","cautela_itens","configuracoes"],marcadores=obrigatorias.map(()=>"?").join(",");copia.all(`SELECT name FROM sqlite_master WHERE type='table' AND name IN (${marcadores})`,obrigatorias,(erroSchema,linhas)=>{const encontradas=new Set((linhas||[]).map(linha=>linha.name)),ausentes=obrigatorias.filter(nome=>!encontradas.has(nome));copia.close(erroFechar=>{if(erroSchema||erroFechar)return reject(erroSchema||erroFechar);if(ausentes.length)return reject(new Error(`O arquivo não é um backup compatível com esta aplicação. Tabelas ausentes: ${ausentes.join(", ")}.`));resolve({arquivo,tamanho:fs.statSync(arquivo).size});});});});});});}
    executarBackupSqlite(destino){return new Promise((resolve,reject)=>{let finalizado=false;const concluir=erro=>{if(finalizado)return;finalizado=true;erro?reject(erro):resolve(destino);};const backup=db.backup(destino,erro=>{if(erro)return concluir(erro);backup.step(-1,(erroPasso,completo)=>{if(erroPasso)return concluir(erroPasso);if(!completo)return concluir(new Error("O SQLite não concluiu a cópia do banco de dados."));concluir();});});});}
    async backupBanco(destino){const origem=this.caminhoBanco();if(path.resolve(destino)===path.resolve(origem))throw new Error("Escolha um destino diferente do banco de dados em uso.");fs.mkdirSync(path.dirname(destino),{recursive:true});const temporario=path.join(path.dirname(destino),`.${path.basename(destino)}.${process.pid}.${Date.now()}.tmp`);try{await this.executarBackupSqlite(temporario);await this.validarBanco(temporario);await fs.promises.copyFile(temporario,destino);await this.validarBanco(destino);return destino;}finally{try{await fs.promises.unlink(temporario);}catch(erro){if(erro.code!=="ENOENT")console.error("Limpeza do backup temporário:",erro.message);}}}
    async copiarGoogleDrive(arquivo){const cfg=this.preferencias();if(!cfg.googleDriveAtivo||!cfg.pastaGoogleDrive)return null;if(!fs.existsSync(cfg.pastaGoogleDrive))throw new Error("A pasta configurada para o Google Drive não está disponível.");const pasta=path.join(cfg.pastaGoogleDrive,"Cautela Demo Backups");fs.mkdirSync(pasta,{recursive:true});const destino=path.join(pasta,path.basename(arquivo));await fs.promises.copyFile(arquivo,destino);return destino;}
    async criarBackupDiario(forcar=false){const destino=this.statusDestinoDiario(),pasta=destino.pastaBackupDiarioEfetiva,arquivo=path.join(pasta,`backup_${this.data()}.db`);if(forcar||!fs.existsSync(arquivo))await this.backupBanco(arquivo);let googleDrive=null;try{googleDrive=await this.copiarGoogleDrive(arquivo);}catch(erro){console.error("Backup no Google Drive:",erro.message);}const retencao=await this.limparBackupsDiariosAntigos();return {arquivo,googleDrive,automatico:!forcar,destino,retencao};}
    horarioValido(valor){return /^([01]\d|2[0-3]):[0-5]\d$/.test(String(valor||""));}
    proximaExecucao(){const hora=this.preferencias().horaBackup||"23:55",[h,m]=hora.split(":").map(Number),agora=new Date(),proxima=new Date(agora);proxima.setHours(h,m,0,0);if(proxima<=agora)proxima.setDate(proxima.getDate()+1);return proxima;}
    async garantirBackupPendente(){if(!this.preferencias().backupDiarioAtivo)return null;const hora=this.preferencias().horaBackup||"23:55",[h,m]=hora.split(":").map(Number),agora=new Date();if((agora.getHours()*60+agora.getMinutes())>=(h*60+m))return this.criarBackupDiario(false);return null;}
    agendarBackupDiario(){if(this.timerBackupDiario){clearTimeout(this.timerBackupDiario);this.timerBackupDiario=null;}if(!this.preferencias().backupDiarioAtivo)return null;const proxima=this.proximaExecucao(),espera=Math.max(1000,proxima.getTime()-Date.now());this.timerBackupDiario=setTimeout(async()=>{try{await this.criarBackupDiario(false);}catch(erro){console.error("Backup diário agendado:",erro);}finally{this.agendarBackupDiario();}},espera);return proxima.toISOString();}
    async iniciarAgendamento(){await this.limparBackupsDiariosAntigos();await this.garantirBackupPendente();return this.agendarBackupDiario();}
    configurarBackupDiario(ativo){const preferencias=this.salvarPreferencias({backupDiarioAtivo:Boolean(ativo)}),proximaExecucao=this.agendarBackupDiario();return {...preferencias,proximaExecucao};}
    configurarHorario(hora){if(!this.horarioValido(hora))throw new Error("Informe um horário válido para o backup diário.");const preferencias=this.salvarPreferencias({horaBackup:hora});const proximaExecucao=this.agendarBackupDiario();return {...preferencias,proximaExecucao};}
    arquivosDaPasta(raiz,excluir=new Set()){const saida=[];const visitar=pasta=>{for(const entrada of fs.readdirSync(pasta,{withFileTypes:true})){const absoluto=path.join(pasta,entrada.name),relativo=path.relative(raiz,absoluto).replaceAll("\\","/");if(excluir.has(entrada.name)||excluir.has(relativo)||entrada.name.endsWith(".log"))continue;if(entrada.isDirectory())visitar(absoluto);else saida.push({absoluto,relativo,data:fs.statSync(absoluto).mtime});}};visitar(raiz);return saida;}
    criarZip(destino,arquivos){fs.mkdirSync(path.dirname(destino),{recursive:true});const fd=fs.openSync(destino,"w"),centrais=[];let offset=0,concluido=false;try{for(const arquivo of arquivos){const dados=leituraFs.readFileSync(arquivo.absoluto),nome=Buffer.from(arquivo.relativo,"utf8"),crc=crc32(dados),tempo=dataZip(arquivo.data),cab=Buffer.alloc(30);if(dados.length>0xffffffff||offset>0xffffffff)throw new Error("A exportação excede o limite de 4 GB do formato ZIP suportado.");cab.writeUInt32LE(0x04034b50,0);cab.writeUInt16LE(20,4);cab.writeUInt16LE(0x800,6);cab.writeUInt16LE(0,8);cab.writeUInt16LE(tempo.hora,10);cab.writeUInt16LE(tempo.dia,12);cab.writeUInt32LE(crc,14);cab.writeUInt32LE(dados.length,18);cab.writeUInt32LE(dados.length,22);cab.writeUInt16LE(nome.length,26);fs.writeSync(fd,cab);fs.writeSync(fd,nome);fs.writeSync(fd,dados);centrais.push({nome,crc,tamanho:dados.length,tempo,offset});offset+=cab.length+nome.length+dados.length;}if(centrais.length>0xffff)throw new Error("A exportação excede o limite de 65.535 arquivos do formato ZIP suportado.");const inicioCentral=offset;for(const item of centrais){const cab=Buffer.alloc(46);cab.writeUInt32LE(0x02014b50,0);cab.writeUInt16LE(20,4);cab.writeUInt16LE(20,6);cab.writeUInt16LE(0x800,8);cab.writeUInt16LE(0,10);cab.writeUInt16LE(item.tempo.hora,12);cab.writeUInt16LE(item.tempo.dia,14);cab.writeUInt32LE(item.crc,16);cab.writeUInt32LE(item.tamanho,20);cab.writeUInt32LE(item.tamanho,24);cab.writeUInt16LE(item.nome.length,28);cab.writeUInt32LE(item.offset,42);fs.writeSync(fd,cab);fs.writeSync(fd,item.nome);offset+=cab.length+item.nome.length;}const fim=Buffer.alloc(22);fim.writeUInt32LE(0x06054b50,0);fim.writeUInt16LE(centrais.length,8);fim.writeUInt16LE(centrais.length,10);fim.writeUInt32LE(offset-inicioCentral,12);fim.writeUInt32LE(inicioCentral,16);fs.writeSync(fd,fim);concluido=true;}finally{fs.closeSync(fd);if(!concluido){try{fs.unlinkSync(destino);}catch{}}}return destino;}
    async exportarCompleto(destino){throw new Error("Use npm run demo:export para gerar o pacote p?blico.");}
    async exportarCompletoLegado(destino){const raiz=path.join(__dirname,".."),temporario=fs.mkdtempSync(path.join(os.tmpdir(),"cautela-demo-completo-")),banco=path.join(temporario,"banco","sistema.db");try{await this.backupBanco(banco);const destinoRelativo=path.relative(raiz,destino).replaceAll("\\","/");const arquivos=this.arquivosDaPasta(raiz,new Set([".git","backup",".tmp-documents","sistema.db","sistema.db-wal","sistema.db-shm",destinoRelativo]));arquivos.push({absoluto:banco,relativo:"banco/sistema.db",data:new Date()});this.criarZip(destino,arquivos);return {arquivo:destino};}finally{fs.rmSync(temporario,{recursive:true,force:true});}}
    async exportarAtualizacao(destino){throw new Error("Use npm run demo:export para gerar o pacote p?blico.");}
    async exportarAtualizacaoLegado(destino){const raiz=path.join(__dirname,".."),temporario=fs.mkdtempSync(path.join(os.tmpdir(),"cautela-demo-atualizacao-"));try{const destinoRelativo=path.relative(raiz,destino).replaceAll("\\","/"),arquivos=this.arquivosDaPasta(raiz,new Set([".git","backup",".tmp-documents","banco",destinoRelativo])),pacote=JSON.parse(fs.readFileSync(path.join(raiz,"package.json"),"utf8")),manifesto={tipo:"ATUALIZACAO_CAUTELA_DEMO",versaoSistema:pacote.version||"1.0.0",geradoEm:new Date().toISOString(),bancoIncluido:false,instrucoes:["Feche completamente a aplicação na máquina de destino.","Extraia este pacote sobre a pasta da instalação existente.","Não remova nem substitua a pasta banco da máquina de destino.","Abra a aplicação e confira os dados e a configuração dos backups."]},manifestoPath=path.join(temporario,"ATUALIZACAO_CAUTELA_DEMO.json");fs.writeFileSync(manifestoPath,JSON.stringify(manifesto,null,2));arquivos.push({absoluto:manifestoPath,relativo:"ATUALIZACAO_CAUTELA_DEMO.json",data:new Date()});this.criarZip(destino,arquivos);return {arquivo:destino,tipo:manifesto.tipo,bancoIncluido:false};}finally{fs.rmSync(temporario,{recursive:true,force:true});}}
    executarBanco(arquivo,sql){return new Promise((resolve,reject)=>{const copia=new sqlite3.Database(arquivo,erro=>{if(erro)return reject(erro);copia.exec(sql,erroExec=>copia.close(erroClose=>erroExec||erroClose?reject(erroExec||erroClose):resolve()));});});}
    async exportarModelo(destino){const temporario=fs.mkdtempSync(path.join(os.tmpdir(),"cautela-demo-modelo-")),banco=path.join(temporario,"banco_modelo.db");try{await this.backupBanco(banco);await this.executarBanco(banco,"PRAGMA foreign_keys=OFF; DELETE FROM historico; DELETE FROM cautela_itens; DELETE FROM cautelas; DELETE FROM policiais_externos; DELETE FROM equipamentos; DELETE FROM sessao; DELETE FROM usuarios; DELETE FROM sqlite_sequence;");const configuracao=await new Promise((resolve,reject)=>db.get("SELECT * FROM configuracoes WHERE id=1",[],(erro,linha)=>erro?reject(erro):resolve(linha||{})));const manifesto={tipo:"MODELO_UNIDADE",versao:1,geradoEm:new Date().toISOString(),configuracao,categoriasEquipamentos:["ARMA_LONGA","ARMA_CURTA","RADIO","COLETE","MUNICAO","OUTROS"],tiposArmamentos:["ARMA_LONGA","ARMA_CURTA"],perfisAcesso:["ADMINISTRADOR","ARMEIRO","COMANDANTE","CONSULTA"],modelosRelatorios:["CAUTELA","EQUIPAMENTOS","POLICIAIS"]};const manifestoPath=path.join(temporario,"modelo-unidade.json");fs.writeFileSync(manifestoPath,JSON.stringify(manifesto,null,2));this.criarZip(destino,[{absoluto:banco,relativo:"banco_modelo.db",data:new Date()},{absoluto:manifestoPath,relativo:"modelo-unidade.json",data:new Date()}]);return {arquivo:destino};}finally{fs.rmSync(temporario,{recursive:true,force:true});}}
}
module.exports=new BackupService();
