(() => {
    const el=id=>document.getElementById(id);
    const seguro=valor=>String(valor??"").replace(/[&<>"']/g,c=>({"&":"&amp;","<":"&lt;",">":"&gt;",'"':"&quot;","'":"&#39;"}[c]));
    const mensagem=(texto,erro=false)=>{const area=el("mensagemBackup");area.textContent=texto;area.classList.toggle("erro",erro);area.classList.add("visivel");};
    const executar=async(botao,rotulo,acao)=>{const original=botao.innerHTML;try{botao.disabled=true;botao.innerHTML='<i class="fa-solid fa-spinner fa-spin"></i> Processando...';const resultado=await acao();if(resultado&&!resultado.cancelado)mensagem(`${rotulo}: ${resultado.arquivo}${resultado.googleDrive?` · Google Drive: ${resultado.googleDrive}`:""}`);return resultado;}catch(erro){mensagem(erro.message||"Não foi possível concluir a operação.",true);}finally{botao.disabled=false;botao.innerHTML=original;}};
    async function atualizarStatus(){const status=await window.api.backup.obterStatus(),ativo=Boolean(status.googleDriveAtivo&&status.pastaGoogleDrive),diarioAtivo=status.backupDiarioAtivo!==false,destino=el("statusDestinoBackupDiario"),personalizado=Boolean(status.pastaBackupDiarioConfigurada),fallback=personalizado&&!status.pastaBackupDiarioDisponivel;el("statusGoogleDrive").innerHTML=ativo?`<i class="fa-solid fa-circle-check"></i><span><b>Cópia automática ativa</b><small>${seguro(status.pastaGoogleDrive)}</small></span>`:'<i class="fa-solid fa-circle-xmark"></i><span><b>Não configurado</b><small>Selecione a pasta local sincronizada pelo Google Drive.</small></span>';el("statusGoogleDrive").classList.toggle("ativo",ativo);el("btnDesativarGoogleDrive").hidden=!ativo;destino.innerHTML=fallback?`<i class="fa-solid fa-triangle-exclamation"></i><span><b>Pasta personalizada indisponível — usando a pasta padrão</b><small>${seguro(status.pastaBackupDiarioEfetiva)} · Configurada: ${seguro(status.pastaBackupDiarioConfigurada)}</small></span>`:`<i class="fa-solid ${personalizado?"fa-folder-circle-check":"fa-folder"}"></i><span><b>${personalizado?"Pasta personalizada ativa":"Pasta padrão"}</b><small>${seguro(status.pastaBackupDiarioEfetiva)}</small></span>`;destino.classList.toggle("fallback",fallback);destino.classList.toggle("ativo",!fallback);el("btnRestaurarPastaBackupDiario").hidden=!personalizado;el("backupDiarioAtivo").checked=diarioAtivo;el("horarioBackupDiario").disabled=!diarioAtivo;el("btnSalvarHorarioBackup").disabled=!diarioAtivo;el("seloBackupAutomatico").innerHTML=diarioAtivo?'<i class="fa-solid fa-shield-halved"></i> Backup diário ativo':'<i class="fa-solid fa-shield"></i> Backup diário desativado';el("seloBackupAutomatico").classList.toggle("inativo",!diarioAtivo);el("horarioBackupDiario").value=status.horaBackup||"23:55";const proxima=status.proximaExecucao?new Date(status.proximaExecucao):null;el("proximoBackupDiario").textContent=diarioAtivo&&proxima&&!Number.isNaN(proxima.getTime())?`Próxima execução: ${proxima.toLocaleString("pt-BR")}`:"Backup automático desativado.";}
    el("btnCriarBackup").onclick=evento=>executar(evento.currentTarget,"Backup criado",()=>window.api.backup.salvar());
    el("btnCriarBackupDiario").onclick=evento=>{mensagem("Backup diário em andamento. Aguarde a conclusão...");return executar(evento.currentTarget,"Backup diário atualizado",()=>window.api.backup.criarDiario());};
    el("btnExportarSistemaCompleto").onclick=evento=>executar(evento.currentTarget,"Sistema completo exportado",()=>window.api.backup.exportarCompleto());
    el("btnExportarAtualizacao").onclick=evento=>executar(evento.currentTarget,"Pacote de atualização exportado",()=>window.api.backup.exportarAtualizacao());
    el("btnExportarModeloUnidade").onclick=evento=>executar(evento.currentTarget,"Modelo da unidade exportado",()=>window.api.backup.exportarModelo());
    el("btnSalvarHorarioBackup").onclick=async evento=>{const hora=el("horarioBackupDiario").value;if(!hora)return mensagem("Informe o horário do backup diário.",true);const resultado=await executar(evento.currentTarget,"Horário do backup atualizado",()=>window.api.backup.configurarHorario(hora));if(resultado)await atualizarStatus();};
    el("backupDiarioAtivo").onchange=async evento=>{const ativo=evento.currentTarget.checked;try{await window.api.backup.configurarBackupDiario(ativo);await atualizarStatus();mensagem(`Backup diário automático ${ativo?"ativado":"desativado"}.`);}catch(erro){evento.currentTarget.checked=!ativo;mensagem(erro.message||"Não foi possível alterar o backup automático.",true);}};
    el("btnEscolherPastaBackupDiario").onclick=async evento=>{const botao=evento.currentTarget,original=botao.innerHTML;try{botao.disabled=true;botao.innerHTML='<i class="fa-solid fa-spinner fa-spin"></i> Selecionando...';const resultado=await window.api.backup.configurarPastaDiaria();if(!resultado.cancelado){await atualizarStatus();mensagem(`Pasta dos backups diários atualizada: ${resultado.pastaBackupDiarioEfetiva}`);}}catch(erro){mensagem(erro.message||"Não foi possível configurar a pasta dos backups diários.",true);}finally{botao.disabled=false;botao.innerHTML=original;}};
    el("btnRestaurarPastaBackupDiario").onclick=async()=>{try{const resultado=await window.api.backup.restaurarPastaDiariaPadrao();await atualizarStatus();mensagem(`Pasta padrão restaurada: ${resultado.pastaBackupDiarioEfetiva}`);}catch(erro){mensagem(erro.message||"Não foi possível restaurar a pasta padrão.",true);}};
    el("btnConfigurarGoogleDrive").onclick=async evento=>{const resultado=await executar(evento.currentTarget,"Google Drive configurado",()=>window.api.backup.configurarGoogleDrive(true));if(resultado&&!resultado.cancelado)await atualizarStatus();};
    el("btnDesativarGoogleDrive").onclick=async()=>{await window.api.backup.configurarGoogleDrive(false);await atualizarStatus();mensagem("Cópia automática para o Google Drive desativada.");};
    el("btnRestaurarBackup").onclick=async()=>{if(!confirm("A restauração substituirá todos os dados atuais e reiniciará o sistema. Deseja continuar?"))return;try{await window.api.backup.restaurar();}catch(erro){mensagem(erro.message||"Não foi possível restaurar o backup.",true);}};
    atualizarStatus().catch(erro=>mensagem(erro.message,true));
})();
